### ISSUE TITLE
Deploy Azure Kubernetes Service (AKS) cluster and connect it to Azure Arc using Azure ARM template

### ISSUE THREAD

**Issue by danielkon96** [likamrat/azure_arc#28]
**Describe the bug**
When deploying the ARM template, I get a specific error about the AgentPoolK8sVersionNotSupported: `"Version 1.17.3 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list"`

**To Reproduce**
1. Go to 'azure_arc/azure_arc_k8s_jumpstart/docs/'
2. Click on 'aks_arm_template.md'
3. Scroll down to 'Deployment'
4. Deploy the ARM template
5. See error:

`{'additionalProperties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'arcaksdemo01' is not valid according to the validation procedure. The tracking id is '*********-***-***-***-*********'. See inner errors for details.", 'target': None, 'details': [{'additionalProperties': {}, 'code': 'AgentPoolK8sVersionNotSupported', 'message': 'Provisioning of resource(s) for container service testinganotheraks in resource group Arc-K3s-Demos failed. Message: {\n  "code": "AgentPoolK8sVersionNotSupported",\n  "message": "Version 1.17.3 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list"\n }. Details: ', 'target': None, 'details': None, 'additionalInfo': None}], 'additionalInfo': None}`

**Expected behavior**
A new AKS cluster in a new Azure Resource Group is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/31390640/83580765-bb9e2a80-a4f1-11ea-92f4-6c7ae17f10a4.png)

**How to resolve error**
To fix the bug, I went into the ARM template 'azuredeploy.json', scrolled down and found "kubernetesVersion" and changed the default value to a version available in the Azure region. I found available Kubernetes versions by running the command `az aks get-versions -l <The region you are deploying to>`

**Comment by likamrat** [comment]
Fixed

https://github.com/likamrat/azure_arc/commit/a8f0a78857b45233bd5a677a8cd90a1a067558b1
