### ISSUE TITLE
Suggestions/issues during walkthrough 

### ISSUE THREAD

**Issue by lastcoolnameleft** [likamrat/azure_arc#30]
https://github.com/likamrat/azure_arc/blob/master/azure_arc_k8s_jumpstart/docs/onboard_k8s.md

Issues:
* When creating RG:  only specific Locations work
```
Connected cluster resource creation is supported only in the following locations: eastus, westeurope, eastus2euap. Use the --location flag to specify one of these locations.
```

Recommendations:

* `az ad sp create-for-rbac` generates string with quotes in it which can cause script to fail.  Might be worth noting.  I thought it used to generate a GUID for the password.
* Don’t use separate script for install.  Makes assumptions about OS, packager (e.g. Linux, snap)
	* Recommend listing prereqs instead like you did for Provider

**Comment by likamrat** [comment]
Fixed. @lastcoolnameleft can you please review?
https://github.com/likamrat/azure_arc/commit/73608cc3040218645680408542dac953d89a8086

**Comment by lastcoolnameleft** [comment]
LGTM!
