### ISSUE TITLE
Support for a Windows Server GCP instance deployment using Terraform

### ISSUE THREAD

**Issue by likamrat** [likamrat/azure_arc#6]
### Description

Support for a lightweight Windows Server GCP VM deployment with Arc connectivity using Terraform

### Implementation Requirments 

- Lightweight VM for fast provisioning
- Parameterize deployment using Terraform
- Azure Arc connectivity instructions
- Detailed README
- Reference in the main README 

### Supporting Docs

[Please refer to the supported Azure Arc supported OS](https://docs.microsoft.com/en-us/azure/azure-arc/servers/overview)

**Comment by youf05** [comment]
This should now be addressed after merging https://github.com/likamrat/azure_arc/pull/13

**Comment by likamrat** [comment]
Resolved
https://github.com/likamrat/azure_arc/blob/master/azure_arc_servers_jumpstart/docs/gcp_terraform_windows.md
